### ISSUE TITLE
No method works for authorization

### ISSUE THREAD

**Issue by Efunch** [dylandoamaral/trakt-integration#84] opened 2023-09-16 22:05 UTC
To the best of my knowledge, I've followed all of the directions, but I can't get the integration to authorize with Trakt. I tried with my direct url to HA and then tried the work-around method, but couldn't successfully authorize either way.

**Comment by Efunch** [comment] 2023-09-16 22:06
I'm running HA OS and have no other issues with my setup at all.

**Comment by Efunch** [comment] 2023-09-16 22:11
trakt_tv:
  language: en # Prefered language for movie/show title
  timezone: America/Chicago # Prefered timezone
  sensors:
    upcoming:
      show:
        days_to_fetch: 90 # How many days in the future you want to fetch
        max_medias: 3 # How many medias you want to fetch
      new_show:
        days_to_fetch: 90
        max_medias: 3
      premiere:
        days_to_fetch: 90
        max_medias: 3
      movie:
        days_to_fetch: 90
        max_medias: 3
      dvd:
        days_to_fetch: 90
        max_medias: 3
    next_to_watch:
      all:
        max_medias: 40
      only_aired:
        max_medias: 40
      only_upcoming:
        max_medias: 40

**Comment by Efunch** [comment] 2023-09-16 22:36
trakt error

TRAKT
OAUTH ERROR
The requested redirect uri is malformed or doesn't match client redirect URI.

**Comment by dylandoamaral** [comment] 2023-09-17 08:41
Did you follow this: https://github.com/dylandoamaral/trakt-integration#workaround ?

**Comment by Efunch** [comment] 2023-09-17 11:11
Yes, I did. It seems to try to redirect to HA, but it's as if some kind of information is missing. The HA my.home-assistant.io/ page says 'invalid parameters given'.


![Trakt Authorization error](https://github.com/dylandoamaral/trakt-integration/assets/52681502/f00d8c93-a32a-4bfe-ab10-f10ae839f219)

**Comment by Efunch** [comment] 2023-09-17 11:24
I can also change my HA link(10.0.0.25:8123) on the 'my.home-assistant.io/' page to '10.0.0.25:8123/oauth, but the page drops the /oauth part every time I try to update the new link. I can make a link to anything other than the oauth part of my HA.


![HA Link Page Error Part 1](https://github.com/dylandoamaral/trakt-integration/assets/52681502/32fa58d9-6edc-45db-b5a1-978f7a21c336)


![HA Link Page Error Part 2](https://github.com/dylandoamaral/trakt-integration/assets/52681502/d73b4323-588b-4a7f-b211-c4d402f6e4a0)


![HA Link Page Error Part 3](https://github.com/dylandoamaral/trakt-integration/assets/52681502/2d1878d2-3755-4b1a-b240-ccc418015ec4)

**Comment by spezzuti** [comment] 2023-10-12 14:08
Same. Over the course of 2 years I have never ONCE had Trakt integrate properly bc oauth fails every single time

**Comment by MJBarry9** [comment] 2023-12-08 02:17
I'm having the same issue. Invalid parameters with the normal setup and the workaround.

**Comment by derekoharrow** [comment] 2024-02-09 15:07
Any update on this at all? Tried setting it up today, using the workaround.
I've added the app to Trakt, added the trakt integration via HACS and then put in my client id and secret. It goes through the authentication process and says authenticated and setting up trakt, but in the integration it doesn't have any devices or entities.
I've setup the trakt application to use https://my.home-assistant.io/redirect/oauth and in my.home-assistant.io I've tried setting it to both the public DNS name for my HASS site and also for the internal DNS name and even the internal IP address - same result...

**Comment by dylandoamaral** [comment] 2024-02-09 19:28
No sadly I can't reproduce it thus can't fix it. If you are willing to put some time, you could change the files yourself to see how to resolve it.

**Comment by derekoharrow** [comment] 2024-02-13 16:16
> No sadly I can't reproduce it thus can't fix it. If you are willing to put some time, you could change the files yourself to see how to resolve it.

Sadly, I'm not a developer so I think that would be beyond me. I'm more than happy to help with testing, debugging, providing logs, etc. though.

**Comment by dylandoamaral** [comment] 2024-08-22 06:12
Close this issue, reopen it if it is still an issue.

**Closed by dylandoamaral** 2024-08-22 06:12 UTC
Labels: bug
